### ISSUE TITLE
Structure and code orgnising techniques

### ISSUE THREAD

**Issue by ahtasham637** [fChristenson/fmail#1]
Hi Fedrik, I am one of your subscriber on your youtube channel.  I am very passionate js developer but some things i lack are structuring and organizing a code in a way that is more reusable and maintainable. I came to this repo after watching your video

https://www.youtube.com/watch?v=ACzMbQEq_tw&t=522s

Can you please guide, what techniques do you use? Any reference? Any tutorial series etc?

**Comment by fChristenson** [comment]
I have a video called "The boring server architecture" that should help.

It will be hard for me to give you answer to all these questions in a single comment since it is years of experience I would have to explain, this is why I can make videos every day so I can share everything I have learned so far in a way that makes sense (I hope).
